### ISSUE TITLE
Arduino error.

### ISSUE THREAD

**Issue by AngelMalus** [Seeed-Studio/OLED_Display_128X64#1]
I do all the setup instructions and when I run Arduino code I get this error, please help.

Arduino: 1.6.5 (Mac OS X), Board: "Arduino Uno"
In file included from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/WString.h:29:0,
                 from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Print.h:26,
                 from /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Stream.h:26,
                 from /Users/Ryuuzaki/Documents/Arduino/libraries/Wire/Wire.h:26,
                 from OLED_Bitmap_Inverse_Display.pde:1:
OLED_Bitmap_Inverse_Display:5: error: variable 'SeeedLogo' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
Multiple libraries were found for "Wire.h"
 Used: /Users/Ryuuzaki/Documents/Arduino/libraries/Wire
 Not used: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr/libraries/Wire
Multiple libraries were found for "SeeedOLED.h"
 Used: /Users/Ryuuzaki/Documents/Arduino/libraries/SeeedOLED
 Not used: /Users/Ryuuzaki/Documents/Arduino/libraries/OLED_Display_128X64-master
variable 'SeeedLogo' must be const in order to be put into read-only section by means of '**attribute**((progmem))'

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by gavinchoate** [comment]
I've recently committed changes that should address these specific issues (eg. error: variable 'SeeedLogo' must be const in order to be put into read-only section by means of 'attribute((progmem))' )

**Comment by KillingJacky** [comment]
Thank you, gavinchoate.
