### ISSUE TITLE
turn on/off display

### ISSUE THREAD

**Issue by TobiasVdb** [Seeed-Studio/OLED_Display_128X64#11]
Please expose following turn off / turn on display calls.

- sendCommand(SeeedOLED_Display_Off_Cmd);     //display off
- sendCommand(SeeedOLED_Display_On_Cmd);  //display on

**Comment by lanselambor** [comment]
@TobiasVdb 
```
void SeeedOLED::sendCommand(unsigned char command)
{
  Wire.beginTransmission(SeeedOLED_Address); // begin I2C communication
#if defined(ARDUINO) && ARDUINO >= 100
  Wire.write(SeeedOLED_Command_Mode);        // Set OLED Command mode
  Wire.write(command);
#else
  Wire.send(SeeedOLED_Command_Mode);         // Set OLED Command mode
  Wire.send(command);
#endif
  Wire.endTransmission();                // End I2C communication
}
```

See sendCommand function, it's a I2C writing procession, for the call __sendCommand(SeeedOLED_Display_Off_Cmd)__  byte __SeeedOLED_Display_Off_Cmd__ was sent to register address __SeeedOLED_Command_Mode__.
