### ISSUE TITLE
Looking for SetPixel(x,y) 

### ISSUE THREAD

**Issue by arunmagesh** [Seeed-Studio/OLED_Display_128X64#6]
I am looking to modify the library to build a function so i can enable each pixel individual. 
Any help??

**Comment by awong1900** [comment]
you can also refer to the GROVE- OLED Display 96x96 to learn how to make 128x64 images to show on this module.

**Comment by KillingJacky** [comment]
from the datasheet of the controller of this display, the data writing is issued by a basic unit of BYTE, it has no bit refreshing support.
datasheet url: https://github.com/SeeedDocument/Grove_OLED_Display_0.96/raw/master/resource/SSD1308_1.0.pdf

So if you want to refresh 1 bit, you need to maintain a graphic buffer, and change the bit in the buffer first, then write the corresponding BYTE (in which the changing bit lies) into the hardware.
